/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SimulatorRouteImport } from './routes/simulator'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as ExecutionOrderRouteImport } from './routes/execution-order'
import { Route as CheatsheetRouteImport } from './routes/cheatsheet'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuizIndexRouteImport } from './routes/quiz.index'
import { Route as LearnIndexRouteImport } from './routes/learn.index'
import { Route as QuizDomainRouteImport } from './routes/quiz.$domain'
import { Route as PhasePhaseIdRouteImport } from './routes/phase.$phaseId'
import { Route as LearnLessonIdRouteImport } from './routes/learn.$lessonId'
import { Route as PhaseRouteImport } from './routes/phase.'

const SimulatorRoute = SimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutionOrderRoute = ExecutionOrderRouteImport.update({
  id: '/execution-order',
  path: '/execution-order',
  getParentRoute: () => rootRouteImport,
} as any)
const CheatsheetRoute = CheatsheetRouteImport.update({
  id: '/cheatsheet',
  path: '/cheatsheet',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizIndexRoute = QuizIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => QuizRoute,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LearnRoute,
} as any)
const QuizDomainRoute = QuizDomainRouteImport.update({
  id: '/$domain',
  path: '/$domain',
  getParentRoute: () => QuizRoute,
} as any)
const PhasePhaseIdRoute = PhasePhaseIdRouteImport.update({
  id: '/phase/$phaseId',
  path: '/phase/$phaseId',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnLessonIdRoute = LearnLessonIdRouteImport.update({
  id: '/$lessonId',
  path: '/$lessonId',
  getParentRoute: () => LearnRoute,
} as any)
const PhaseRoute = PhaseRouteImport.update({
  id: '/phase/',
  path: '/phase/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cheatsheet': typeof CheatsheetRoute
  '/execution-order': typeof ExecutionOrderRoute
  '/learn': typeof LearnRouteWithChildren
  '/quiz': typeof QuizRouteWithChildren
  '/simulator': typeof SimulatorRoute
  '/phase/': typeof PhaseRoute
  '/learn/$lessonId': typeof LearnLessonIdRoute
  '/phase/$phaseId': typeof PhasePhaseIdRoute
  '/quiz/$domain': typeof QuizDomainRoute
  '/learn/': typeof LearnIndexRoute
  '/quiz/': typeof QuizIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cheatsheet': typeof CheatsheetRoute
  '/execution-order': typeof ExecutionOrderRoute
  '/simulator': typeof SimulatorRoute
  '/phase': typeof PhaseRoute
  '/learn/$lessonId': typeof LearnLessonIdRoute
  '/phase/$phaseId': typeof PhasePhaseIdRoute
  '/quiz/$domain': typeof QuizDomainRoute
  '/learn': typeof LearnIndexRoute
  '/quiz': typeof QuizIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cheatsheet': typeof CheatsheetRoute
  '/execution-order': typeof ExecutionOrderRoute
  '/learn': typeof LearnRouteWithChildren
  '/quiz': typeof QuizRouteWithChildren
  '/simulator': typeof SimulatorRoute
  '/phase/': typeof PhaseRoute
  '/learn/$lessonId': typeof LearnLessonIdRoute
  '/phase/$phaseId': typeof PhasePhaseIdRoute
  '/quiz/$domain': typeof QuizDomainRoute
  '/learn/': typeof LearnIndexRoute
  '/quiz/': typeof QuizIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cheatsheet'
    | '/execution-order'
    | '/learn'
    | '/quiz'
    | '/simulator'
    | '/phase/'
    | '/learn/$lessonId'
    | '/phase/$phaseId'
    | '/quiz/$domain'
    | '/learn/'
    | '/quiz/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cheatsheet'
    | '/execution-order'
    | '/simulator'
    | '/phase'
    | '/learn/$lessonId'
    | '/phase/$phaseId'
    | '/quiz/$domain'
    | '/learn'
    | '/quiz'
  id:
    | '__root__'
    | '/'
    | '/cheatsheet'
    | '/execution-order'
    | '/learn'
    | '/quiz'
    | '/simulator'
    | '/phase/'
    | '/learn/$lessonId'
    | '/phase/$phaseId'
    | '/quiz/$domain'
    | '/learn/'
    | '/quiz/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheatsheetRoute: typeof CheatsheetRoute
  ExecutionOrderRoute: typeof ExecutionOrderRoute
  LearnRoute: typeof LearnRouteWithChildren
  QuizRoute: typeof QuizRouteWithChildren
  SimulatorRoute: typeof SimulatorRoute
  PhaseRoute: typeof PhaseRoute
  PhasePhaseIdRoute: typeof PhasePhaseIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/simulator': {
      id: '/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof SimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/execution-order': {
      id: '/execution-order'
      path: '/execution-order'
      fullPath: '/execution-order'
      preLoaderRoute: typeof ExecutionOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cheatsheet': {
      id: '/cheatsheet'
      path: '/cheatsheet'
      fullPath: '/cheatsheet'
      preLoaderRoute: typeof CheatsheetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/': {
      id: '/quiz/'
      path: '/'
      fullPath: '/quiz/'
      preLoaderRoute: typeof QuizIndexRouteImport
      parentRoute: typeof QuizRoute
    }
    '/learn/': {
      id: '/learn/'
      path: '/'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof LearnRoute
    }
    '/quiz/$domain': {
      id: '/quiz/$domain'
      path: '/$domain'
      fullPath: '/quiz/$domain'
      preLoaderRoute: typeof QuizDomainRouteImport
      parentRoute: typeof QuizRoute
    }
    '/phase/$phaseId': {
      id: '/phase/$phaseId'
      path: '/phase/$phaseId'
      fullPath: '/phase/$phaseId'
      preLoaderRoute: typeof PhasePhaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$lessonId': {
      id: '/learn/$lessonId'
      path: '/$lessonId'
      fullPath: '/learn/$lessonId'
      preLoaderRoute: typeof LearnLessonIdRouteImport
      parentRoute: typeof LearnRoute
    }
    '/phase/': {
      id: '/phase/'
      path: '/phase'
      fullPath: '/phase/'
      preLoaderRoute: typeof PhaseRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LearnRouteChildren {
  LearnLessonIdRoute: typeof LearnLessonIdRoute
  LearnIndexRoute: typeof LearnIndexRoute
}

const LearnRouteChildren: LearnRouteChildren = {
  LearnLessonIdRoute: LearnLessonIdRoute,
  LearnIndexRoute: LearnIndexRoute,
}

const LearnRouteWithChildren = LearnRoute._addFileChildren(LearnRouteChildren)

interface QuizRouteChildren {
  QuizDomainRoute: typeof QuizDomainRoute
  QuizIndexRoute: typeof QuizIndexRoute
}

const QuizRouteChildren: QuizRouteChildren = {
  QuizDomainRoute: QuizDomainRoute,
  QuizIndexRoute: QuizIndexRoute,
}

const QuizRouteWithChildren = QuizRoute._addFileChildren(QuizRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheatsheetRoute: CheatsheetRoute,
  ExecutionOrderRoute: ExecutionOrderRoute,
  LearnRoute: LearnRouteWithChildren,
  QuizRoute: QuizRouteWithChildren,
  SimulatorRoute: SimulatorRoute,
  PhaseRoute: PhaseRoute,
  PhasePhaseIdRoute: PhasePhaseIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
